export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_PROFESSORS_SUCCESS = "LOAD_PROFESSORS_SUCCESS";

export const LOAD_ACCOUNTS_SUCCESS = "LOAD_ACCOUNTS_SUCCESS";
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_TRANSACTIONS_SUCCESS = "LOAD_TRANSACTIONS_SUCCESS";

export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";

export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOGIN="LOGIN";

// By convention, actions that end in "_SUCCESS" are assumed to have been the result of a completed
// API call. But since we're doing an optimistic delete, we're hiding loading state.
// So this action name deliberately omits the "_SUCCESS" suffix.
// If it had one, our apiCallsInProgress counter would be decremented below zero
// because we're not incrementing the number of apiCallInProgress when the delete request begins.
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
export const DELETE_PROFESSOR_OPTIMISTIC = "DELETE_PROFESSOR_OPTIMISTIC";

export const DELETE_ACCOUNT_OPTIMISTIC="DELETE_ACCOUNT_OPTIMISTIC";

export const LOAD_PRODUCTS_SUCCESS="LOAD_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_OPTIMISTIC="DELETE_PRODUCT_OPTIMISTIC";

export const LOAD_ORDERS_SUCCESS="LOAD_ORDERS_SUCCESS";
export const LOAD_ORDERRS_SUCCESS="LOAD_ORDERRS_SUCCESS";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS";
export const DELETE_ORDER_OPTIMISTIC="DELETE_ORDER_OPTIMISTIC";

export const LOAD_PURCHASES_SUCCESS="LOAD_PURCHASES_SUCCESS";
export const CREATE_PURCHASE_SUCCESS="CREATE_PURCHASE_SUCCESS";
export const UPDATE_PURCHASE_SUCCESS="UPDATE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_OPTIMISTIC="DELETE_PURCHASE_OPTIMISTIC";



